name: Node.js CI (pnpm)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Or your preferred pnpm version
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Optional: Run a build if you have a build script in package.json
      # - name: Build
      #   run: pnpm run build

      # Since your test script exits with error, either remove or replace this
      - name: Lint (example)
        run: pnpm exec eslint .

      # Or if you want tests later:
      # - name: Test
      #   run: pnpm test
